import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  modulesSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System',
      items: [
        'ros2-nervous-system/ros-fundamentals',
        'ros2-nervous-system/python-agents',
        'ros2-nervous-system/urdf-modeling',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin',
      items: [
        'digital-twin-simulation/physics-simulation',
        'digital-twin-simulation/high-fidelity-interaction',
        'digital-twin-simulation/simulating-sensors',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain',
      items: [
        'isaac-robot-brain/perception-training',
        'isaac-robot-brain/vslam-navigation',
        'isaac-robot-brain/path-planning-nav2',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action',
      items: [
        'vla-capstone/voice-to-action',
        'vla-capstone/cognitive-planning',
        'vla-capstone/capstone-overview',
      ],
    },
  ],
};

export default sidebars;